"""
SOSYAL BILGILER soru bankasi (yalniz 4. sinif).

MUFREDAT NOTU: Sosyal Bilgiler 4. sinifta baslar.
Hayat Bilgisi 4. sinifta biter, yerini Fen + Sosyal alir.

Band hedef dogruluk: 1=%90  2=%75  3=%60  4=%40  5=%20
Format: (band, sinif_min, sinif_max, soru, [siklar], dogru_index, aciklama)
"""

# ==================================================== KIMLIK VE HAKLARIMIZ

KIMLIK_HAKLAR = [
    (1, 4, 4, "Kimlik kartında ne yazar?", ["Ad, soyad, doğum tarihi", "Sadece ad", "Notlarımız", "Adresimiz sadece"], 0, "Kimlik bilgileri"),
    (1, 4, 4, "Her çocuğun en temel hakkı nedir?", ["Yaşama hakkı", "Oyun oynama", "Televizyon izleme", "Geç yatma"], 0, "Yaşama hakkı temeldir"),
    (1, 4, 4, "Eğitim hakkı ne demektir?", ["Herkesin okuma hakkı vardır", "Sadece zenginler okur", "İstersek okuruz", "Okul zorunlu değildir"], 0, "Herkes eğitim alabilir"),
    (1, 4, 4, "Hangisi çocuk hakkıdır?", ["Sağlıklı beslenme", "Çalıştırılma", "İhmal edilme", "Dışlanma"], 0, "Beslenme temel haktır"),
    (2, 4, 4, "Sorumluluk ne demektir?", ["Üstlendiğimiz görevi yerine getirmek", "İstediğimizi yapmak", "Kural tanımamak", "Beklemek"], 0, "Görev bilinci"),
    (2, 4, 4, "Haklarımızın sınırı nedir?", ["Başkalarının hakları", "Sınırsızdır", "Yaşımız", "Paramız"], 0, "Özgürlük başkasının hakkında biter"),
    (2, 4, 4, "Bireysel farklılıklara nasıl davranmalıyız?", ["Saygı göstermeliyiz", "Alay etmeliyiz", "Dışlamalıyız", "Görmezden gelmeliyiz"], 0, "Farklılıklara saygı"),
    (2, 4, 4, "Çocuk Hakları Sözleşmesi neyi korur?", ["Çocukların haklarını", "Yetişkinleri", "Hayvanları", "Bitkileri"], 0, "BM Çocuk Hakları Sözleşmesi"),
    (3, 4, 4, "Kimlik numaramız kaç hanelidir?", ["11", "10", "12", "9"], 0, "T.C. kimlik no 11 hanelidir"),
    (3, 4, 4, "Nüfus cüzdanı hangi kurumdan alınır?", ["Nüfus Müdürlüğü", "Belediye", "Okul", "Hastane"], 0, "Nüfus ve Vatandaşlık İşleri"),
    (3, 4, 4, "Empati ne demektir?", ["Kendini başkasının yerine koymak", "Kavga etmek", "Görmezden gelmek", "Yargılamak"], 0, "Duygudaşlık"),
    (3, 4, 4, "Bir haksızlıkla karşılaşırsak ne yapmalıyız?", ["Yetkililere bildirmeliyiz", "Susmalıyız", "Kaçmalıyız", "Biz de yapmalıyız"], 0, "Haksızlığa sessiz kalmamak"),
    (4, 4, 4, "Kişisel bilgilerimizi kimlerle paylaşmalıyız?", ["Sadece güvendiğimiz büyüklerle", "Herkesle", "İnternette", "Yabancılarla"], 0, "Kişisel veri güvenliği"),
    (4, 4, 4, "Toplumsal rol ne demektir?", ["Toplumda üstlendiğimiz görevler", "Oyun rolü", "Tiyatro rolü", "İsim"], 0, "Öğrenci, evlat, arkadaş vb."),
    (5, 4, 4, "Hak ve sorumluluk arasındaki ilişki nedir?", ["Her hakkın bir sorumluluğu vardır", "İlgisizdir", "Sadece hak vardır", "Sadece sorumluluk vardır"], 0, "Hak ve sorumluluk birlikte"),
    (1, 4, 4, "Adımızı ve soyadımızı nereden öğreniriz?", ["Ailemizden ve kimliğimizden", "Okuldan", "Arkadaşlarımızdan", "Televizyondan"], 0, "Kimlik bilgisi"),
    (1, 4, 4, "Herkes eşit haklara sahip midir?", ["Evet", "Hayır", "Sadece büyükler", "Sadece çocuklar"], 0, "Eşitlik ilkesi"),
    (1, 4, 4, "Sağlık hakkı ne demektir?", ["Herkesin tedavi olma hakkı", "Sadece zenginler", "Sadece hastalar", "Yoktur"], 0, "Temel hak"),
    (1, 4, 4, "Hangisi çocukların sorumluluğudur?", ["Derslerine çalışmak", "Çalışıp para kazanmak", "Ev geçindirmek", "Araba kullanmak"], 0, "Yaşa uygun sorumluluk"),
    (2, 4, 4, "Barınma hakkı ne demektir?", ["Güvenli bir evde yaşama hakkı", "Ev satın alma", "Kira ödememe", "Otelde kalma"], 0, "Temel ihtiyaç hakkı"),
    (2, 4, 4, "Çocuklar çalıştırılabilir mi?", ["Hayır, çocuk işçiliği yasaktır", "Evet", "Bazen", "Yazın"], 0, "Çocuk işçiliği yasak"),
    (2, 4, 4, "Kişisel alan ne demektir?", ["Herkesin kendine ait mahremiyeti", "Odamız", "Bahçemiz", "Okulumuz"], 0, "Mahremiyet"),
    (2, 4, 4, "Ayrımcılık ne demektir?", ["İnsanlara farklılıkları yüzünden kötü davranmak", "Seçim yapmak", "Karar vermek", "Tercih etmek"], 0, "Ayrımcılık yanlıştır"),
    (2, 4, 4, "Hangisi sorumluluk örneğidir?", ["Ödevini zamanında yapmak", "Kural tanımamak", "Beklemek", "İzlemek"], 0, "Görev bilinci"),
    (3, 4, 4, "Kimlik belgemizi kaybedersek ne yaparız?", ["Nüfus Müdürlüğüne bildiririz", "Yenisini yaparız", "Hiçbir şey", "Bekleriz"], 0, "Resmi bildirim"),
    (3, 4, 4, "Çocuk hakları neden vardır?", ["Çocukları korumak ve geliştirmek için", "Kısıtlamak için", "Ceza için", "Gereksizdir"], 0, "Koruma ve gelişim"),
    (3, 4, 4, "Düşünce özgürlüğü ne demektir?", ["Fikirlerimizi özgürce ifade edebilmek", "İstediğimizi yapmak", "Kural tanımamak", "Susmak"], 0, "İfade özgürlüğü"),
    (3, 4, 4, "Başkalarının haklarına saygı neden önemlidir?", ["Toplumsal huzur için", "Zorunlu olduğu için", "Gereksizdir", "Ceza korkusundan"], 0, "Karşılıklı saygı"),
    (4, 4, 4, "Toplumsal cinsiyet eşitliği ne demektir?", ["Kadın ve erkeğin eşit haklara sahip olması", "Kadınların üstünlüğü", "Erkeklerin üstünlüğü", "Ayrım yapmak"], 0, "Eşitlik"),
    (4, 4, 4, "Engelli bireylere nasıl davranmalıyız?", ["Eşit ve saygılı", "Acıyarak", "Görmezden gelerek", "Farklı"], 0, "Eşit muamele"),
]

# ==================================================== ATATURK VE TARIHIMIZ

TARIHIMIZ = [
    (1, 4, 4, "Türkiye Cumhuriyeti ne zaman kurulmuştur?", ["29 Ekim 1923", "23 Nisan 1920", "19 Mayıs 1919", "30 Ağustos 1922"], 0, "29 Ekim 1923"),
    (1, 4, 4, "Cumhuriyetimizin kurucusu kimdir?", ["Mustafa Kemal Atatürk", "İsmet İnönü", "Fatih Sultan Mehmet", "Osman Bey"], 0, "Atatürk"),
    (1, 4, 4, "Başkentimiz neresidir?", ["Ankara", "İstanbul", "İzmir", "Bursa"], 0, "Ankara"),
    (1, 4, 4, "Milli marşımızın adı nedir?", ["İstiklal Marşı", "Gençlik Marşı", "Onuncu Yıl Marşı", "Zafer Marşı"], 0, "İstiklal Marşı"),
    (2, 4, 4, "Kurtuluş Savaşı ne zaman başlamıştır?", ["19 Mayıs 1919", "29 Ekim 1923", "23 Nisan 1920", "30 Ağustos 1922"], 0, "Samsun'a çıkış"),
    (2, 4, 4, "TBMM ne zaman açılmıştır?", ["23 Nisan 1920", "29 Ekim 1923", "19 Mayıs 1919", "10 Kasım 1938"], 0, "23 Nisan 1920"),
    (2, 4, 4, "İstiklal Marşı'nın şairi kimdir?", ["Mehmet Akif Ersoy", "Namık Kemal", "Ziya Gökalp", "Tevfik Fikret"], 0, "Mehmet Akif Ersoy"),
    (2, 4, 4, "Anıtkabir nerededir?", ["Ankara", "İstanbul", "İzmir", "Samsun"], 0, "Ankara"),
    (2, 4, 4, "30 Ağustos hangi zaferin günüdür?", ["Büyük Taarruz", "Çanakkale", "İnönü", "Sakarya"], 0, "Başkomutanlık Meydan Muharebesi"),
    (3, 4, 4, "Atatürk hangi inkılapla yeni harfleri getirmiştir?", ["Harf İnkılabı", "Kılık kıyafet", "Takvim", "Ölçü birimleri"], 0, "1928 Harf İnkılabı"),
    (3, 4, 4, "Kadınlara seçme ve seçilme hakkı ne zaman verilmiştir?", ["1934", "1923", "1928", "1938"], 0, "1934"),
    (3, 4, 4, "Atatürk'ün 'Egemenlik kayıtsız şartsız milletindir' sözü neyi anlatır?", ["Milli egemenliği", "Savaşı", "Ticareti", "Eğitimi"], 0, "Halk egemenliği"),
    (3, 4, 4, "Cumhuriyet öncesi yönetim şekli neydi?", ["Saltanat", "Cumhuriyet", "Demokrasi", "Meclis"], 0, "Osmanlı saltanatı"),
    (3, 4, 4, "Atatürk hangi savaşta 'Ben size taarruzu değil, ölmeyi emrediyorum' demiştir?", ["Çanakkale", "Sakarya", "Dumlupınar", "İnönü"], 0, "Çanakkale Savaşı"),
    (4, 4, 4, "Laiklik ilkesi ne demektir?", ["Din ve devlet işlerinin ayrılması", "Dinsizlik", "Tek din", "Din yasağı"], 0, "Din-devlet ayrımı"),
    (4, 4, 4, "Cumhuriyetçilik ilkesi neyi savunur?", ["Halkın kendini yönetmesini", "Padişahlığı", "Askeri yönetimi", "Tek kişi yönetimini"], 0, "Cumhuriyet yönetimi"),
    (4, 4, 4, "Kültürel miras neden korunmalıdır?", ["Geçmişimizi geleceğe taşır", "Turist gelir sadece", "Para kazandırır", "Gereksizdir"], 0, "Kültürel süreklilik"),
    (5, 4, 4, "Atatürk'ün 'Yurtta sulh, cihanda sulh' ilkesi hangi alandadır?", ["Dış politika", "Eğitim", "Ekonomi", "Sağlık"], 0, "Barışçı dış politika"),
    (5, 4, 4, "Milli mücadelede halkın rolü ne olmuştur?", ["Topyekûn destek vermiştir", "İzlemiştir", "Karşı çıkmıştır", "Karışmamıştır"], 0, "Halkın katılımı"),
    (1, 4, 4, "Atatürk nerede doğmuştur?", ["Selanik", "İstanbul", "Ankara", "İzmir"], 0, "1881, Selanik"),
    (1, 4, 4, "10 Kasım'da neyi anarız?", ["Atatürk'ün vefatını", "Cumhuriyeti", "Zaferi", "Çocukları"], 0, "10 Kasım 1938"),
    (1, 4, 4, "23 Nisan hangi bayramdır?", ["Ulusal Egemenlik ve Çocuk Bayramı", "Cumhuriyet Bayramı", "Zafer Bayramı", "Gençlik Bayramı"], 0, "23 Nisan"),
    (2, 4, 4, "19 Mayıs hangi bayramdır?", ["Gençlik ve Spor Bayramı", "Çocuk Bayramı", "Cumhuriyet Bayramı", "Zafer Bayramı"], 0, "19 Mayıs"),
    (2, 4, 4, "Atatürk'ün annesinin adı nedir?", ["Zübeyde Hanım", "Makbule Hanım", "Fatma Hanım", "Ayşe Hanım"], 0, "Zübeyde Hanım"),
    (2, 4, 4, "Sakarya Meydan Muharebesi'nin önemi nedir?", ["Türk ordusu savunmadan taarruza geçti", "Savaş başladı", "Barış yapıldı", "Cumhuriyet ilan edildi"], 0, "Dönüm noktası"),
    (3, 4, 4, "Tarih öğrenmek neden önemlidir?", ["Geçmişten ders alıp geleceği şekillendirmek için", "Ezber için", "Sınav için", "Gereksizdir"], 0, "Tarih bilinci"),
    (3, 4, 4, "Müzeler ne işe yarar?", ["Tarihi eserleri korur ve sergiler", "Eşya satar", "Kitap satar", "Yemek verir"], 0, "Kültürel miras"),
    (4, 4, 4, "Milliyetçilik ilkesi neyi savunur?", ["Milletin birlik ve beraberliğini", "Diğer milletlere üstünlüğü", "Savaşı", "Ayrılığı"], 0, "Birlik ve beraberlik"),
    (4, 4, 4, "İnkılapçılık ilkesi ne demektir?", ["Çağın gereklerine göre yenilenmek", "Değişmemek", "Geçmişe dönmek", "Beklemek"], 0, "Sürekli yenilenme"),
    (5, 4, 4, "Devletçilik ilkesi neyi ifade eder?", ["Devletin ekonomiye yön vermesi", "Özel sektörün yasaklanması", "Ticaretin durması", "Vergi alınmaması"], 0, "Ekonomik kalkınmada devlet rolü"),
]

# ==================================================== TURKIYE COGRAFYASI

COGRAFYA = [
    (1, 4, 4, "Türkiye hangi kıtalarda yer alır?", ["Asya ve Avrupa", "Sadece Asya", "Sadece Avrupa", "Afrika"], 0, "İki kıtada yer alır"),
    (1, 4, 4, "Türkiye'nin en büyük gölü hangisidir?", ["Van Gölü", "Tuz Gölü", "Beyşehir", "Eğirdir"], 0, "Van Gölü"),
    (1, 4, 4, "Türkiye'nin en uzun nehri hangisidir?", ["Kızılırmak", "Fırat", "Sakarya", "Yeşilırmak"], 0, "Kızılırmak (tamamı Türkiye'de)"),
    (1, 4, 4, "Türkiye'nin en yüksek dağı hangisidir?", ["Ağrı Dağı", "Erciyes", "Uludağ", "Kaçkar"], 0, "Ağrı Dağı (5137 m)"),
    (2, 4, 4, "Türkiye kaç coğrafi bölgeye ayrılır?", ["7", "5", "6", "8"], 0, "7 coğrafi bölge"),
    (2, 4, 4, "İstanbul hangi bölgededir?", ["Marmara", "Ege", "Karadeniz", "İç Anadolu"], 0, "Marmara Bölgesi"),
    (2, 4, 4, "Türkiye'yi çevreleyen denizler kaç tanedir?", ["4", "3", "2", "5"], 0, "Karadeniz, Marmara, Ege, Akdeniz"),
    (2, 4, 4, "Hangi bölgemiz en çok yağış alır?", ["Karadeniz", "İç Anadolu", "Güneydoğu Anadolu", "Ege"], 0, "Karadeniz Bölgesi"),
    (2, 4, 4, "Başkentimiz hangi bölgededir?", ["İç Anadolu", "Marmara", "Ege", "Akdeniz"], 0, "Ankara — İç Anadolu"),
    (3, 4, 4, "Türkiye'nin komşuları arasında hangisi vardır?", ["Yunanistan", "Mısır", "İtalya", "Fransa"], 0, "Kara komşusu"),
    (3, 4, 4, "Ege Bölgesi'nde hangi tarım ürünü öne çıkar?", ["Zeytin", "Çay", "Fındık", "Muz"], 0, "Zeytin ve incir"),
    (3, 4, 4, "Karadeniz Bölgesi'nde hangi ürün yetişir?", ["Çay ve fındık", "Muz", "Zeytin", "Pamuk"], 0, "Çay ve fındık"),
    (3, 4, 4, "İklim ne demektir?", ["Uzun yıllar süren hava durumu ortalaması", "Günlük hava", "Sıcaklık", "Yağmur"], 0, "Uzun süreli hava koşulları"),
    (3, 4, 4, "Akdeniz ikliminin özelliği nedir?", ["Yazları sıcak kurak, kışları ılık yağışlı", "Her mevsim yağışlı", "Her mevsim kurak", "Çok soğuk"], 0, "Akdeniz iklimi"),
    (4, 4, 4, "Türkiye'nin yüzey şekilleri nasıldır?", ["Dağlık ve engebeli", "Tamamen düz", "Sadece ova", "Sadece deniz"], 0, "Ortalama yükseklik fazladır"),
    (4, 4, 4, "Deprem neden olur?", ["Yer kabuğu hareketleri", "Yağmur", "Rüzgar", "Güneş"], 0, "Fay hatları"),
    (4, 4, 4, "Türkiye deprem kuşağında mıdır?", ["Evet", "Hayır", "Kısmen", "Bilinmiyor"], 0, "Alp-Himalaya deprem kuşağı"),
    (5, 4, 4, "Boğazlarımız hangileridir?", ["İstanbul ve Çanakkale", "Sadece İstanbul", "Sadece Çanakkale", "Van ve Tuz"], 0, "İstanbul ve Çanakkale Boğazı"),
    (5, 4, 4, "Türkiye'nin jeopolitik önemi neden fazladır?", ["Üç kıtanın kesişiminde ve boğazlara sahip", "Büyük olduğu için", "Kalabalık olduğu için", "Zengin olduğu için"], 0, "Konum avantajı"),
    (1, 4, 4, "Türkiye'nin kuzeyindeki deniz hangisidir?", ["Karadeniz", "Akdeniz", "Ege", "Marmara"], 0, "Karadeniz"),
    (1, 4, 4, "Türkiye'nin güneyindeki deniz hangisidir?", ["Akdeniz", "Karadeniz", "Ege", "Marmara"], 0, "Akdeniz"),
    (1, 4, 4, "Türkiye'nin batısındaki deniz hangisidir?", ["Ege", "Karadeniz", "Akdeniz", "Marmara"], 0, "Ege Denizi"),
    (2, 4, 4, "Ova nedir?", ["Düz ve alçak arazi", "Yüksek dağ", "Derin vadi", "Su birikintisi"], 0, "Düzlük alan"),
    (2, 4, 4, "İzmir hangi bölgededir?", ["Ege", "Marmara", "Akdeniz", "Karadeniz"], 0, "Ege Bölgesi"),
    (2, 4, 4, "Türkiye'nin en kalabalık şehri hangisidir?", ["İstanbul", "Ankara", "İzmir", "Bursa"], 0, "İstanbul"),
    (3, 4, 4, "Karadeniz Bölgesi neden çok yağış alır?", ["Dağlar denize paralel ve nemli hava yükselir", "Sıcak olduğu için", "Alçak olduğu için", "Rastgele"], 0, "Orografik yağış"),
    (3, 4, 4, "Nüfus yoğunluğu ne demektir?", ["Bir alanda yaşayan kişi sayısı", "Toplam nüfus", "Doğum sayısı", "Göç sayısı"], 0, "Kişi/km²"),
    (4, 4, 4, "Göç neden olur?", ["İş, eğitim ve daha iyi yaşam arayışı", "Sadece savaş", "Sadece iklim", "Rastgele"], 0, "Çok nedenli"),
    (4, 4, 4, "Deprem riskine karşı ne yapılmalı?", ["Sağlam bina ve hazırlık", "Beklemek", "Taşınmak", "Hiçbir şey"], 0, "Yapı güvenliği + hazırlık"),
    (5, 4, 4, "Türkiye'nin matematik konumu neyi etkiler?", ["İklimi ve mevsimleri", "Sadece dili", "Sadece dini", "Hiçbir şeyi"], 0, "Enlem-boylam etkisi"),
]

# ==================================================== BULUSLAR VE TEKNOLOJI

BULUSLAR = [
    (1, 4, 4, "Tekerlek ne işe yarar?", ["Taşımayı kolaylaştırır", "Isıtır", "Aydınlatır", "Ses çıkarır"], 0, "Ulaşım ve taşıma"),
    (1, 4, 4, "Ampulü kim bulmuştur?", ["Thomas Edison", "Graham Bell", "Newton", "Einstein"], 0, "Edison"),
    (1, 4, 4, "Telefon ne işe yarar?", ["Uzaktan konuşmayı sağlar", "Isıtır", "Aydınlatır", "Taşır"], 0, "İletişim aracı"),
    (1, 4, 4, "Bilgisayar ne işe yarar?", ["Bilgi işler ve saklar", "Isıtır", "Yemek pişirir", "Temizler"], 0, "Bilgi işleme"),
    (2, 4, 4, "Matbaanın icadı neyi kolaylaştırmıştır?", ["Kitap çoğaltmayı", "Ulaşımı", "Yemek yapmayı", "İnşaatı"], 0, "Bilginin yayılması"),
    (2, 4, 4, "Telefonu kim bulmuştur?", ["Graham Bell", "Edison", "Newton", "Wright kardeşler"], 0, "Alexander Graham Bell"),
    (2, 4, 4, "Uçağı kimler bulmuştur?", ["Wright kardeşler", "Edison", "Bell", "Newton"], 0, "Wright kardeşler"),
    (2, 4, 4, "İnternet ne sağlar?", ["Bilgiye hızlı erişim ve iletişim", "Isınma", "Beslenme", "Barınma"], 0, "Küresel bilgi ağı"),
    (3, 4, 4, "Hangi Türk bilim insanı uçmayı denemiştir?", ["Hezarfen Ahmet Çelebi", "Piri Reis", "İbn-i Sina", "Ali Kuşçu"], 0, "Hezarfen Ahmet Çelebi"),
    (3, 4, 4, "Piri Reis neyle ünlüdür?", ["Haritalarıyla", "Uçmasıyla", "Tıp bilgisiyle", "Matematikle"], 0, "Dünya haritası"),
    (3, 4, 4, "Teknoloji hayatımızı nasıl etkiler?", ["Kolaylaştırır ama bilinçli kullanılmalı", "Sadece zarar verir", "Sadece fayda sağlar", "Etkilemez"], 0, "İki yönlü etki"),
    (3, 4, 4, "Buluş ile keşif arasındaki fark nedir?", ["Buluş yapılır, keşif bulunur", "Aynıdır", "Buluş bulunur", "Fark yoktur"], 0, "Buluş = yeni üretim, keşif = var olanı bulma"),
    (4, 4, 4, "Bilimsel gelişmeler neye dayanır?", ["Gözlem ve deneye", "Tahmine", "Şansa", "İnanca"], 0, "Bilimsel yöntem"),
    (4, 4, 4, "Teknolojinin olumsuz etkisi ne olabilir?", ["Bağımlılık ve hareketsizlik", "Hiçbiri", "Sadece fayda", "Hızlanma"], 0, "Bilinçsiz kullanım zararı"),
    (5, 4, 4, "İbn-i Sina hangi alanda ünlüdür?", ["Tıp", "Astronomi", "Matematik", "Coğrafya"], 0, "Tıp bilimi, El-Kanun"),
    (1, 4, 4, "Saat ne işe yarar?", ["Zamanı ölçer", "Isıtır", "Aydınlatır", "Taşır"], 0, "Zaman ölçümü"),
    (1, 4, 4, "Buzdolabı ne işe yarar?", ["Besinleri soğutup korur", "Isıtır", "Pişirir", "Temizler"], 0, "Soğutma ve saklama"),
    (1, 4, 4, "Kağıt ne işe yarar?", ["Yazı yazmayı ve bilgi saklamayı sağlar", "Isıtır", "Aydınlatır", "Taşır"], 0, "Bilgi kaydı"),
    (2, 4, 4, "Pusula ne işe yarar?", ["Yön bulmayı sağlar", "Zamanı ölçer", "Isı ölçer", "Ağırlık ölçer"], 0, "Yön bulma"),
    (2, 4, 4, "Mikroskop neyi görmemizi sağlar?", ["Çok küçük varlıkları", "Uzaktaki yıldızları", "Gökyüzünü", "Denizi"], 0, "Küçük cisimleri büyütür"),
    (2, 4, 4, "Teleskop neyi görmemizi sağlar?", ["Uzaydaki gök cisimlerini", "Mikropları", "Hücreleri", "Atomları"], 0, "Uzak cisimleri yakınlaştırır"),
    (2, 4, 4, "Ulaşımı kolaylaştıran buluş hangisidir?", ["Tekerlek", "Ampul", "Telefon", "Kağıt"], 0, "Tekerlek ulaşım devrimi"),
    (3, 4, 4, "Ali Kuşçu hangi alanda çalışmıştır?", ["Astronomi ve matematik", "Tıp", "Coğrafya", "Edebiyat"], 0, "Astronom ve matematikçi"),
    (3, 4, 4, "Bilim insanları nasıl çalışır?", ["Gözlem yapıp deney kurarak", "Tahmin ederek", "Şansa bırakarak", "Rastgele"], 0, "Bilimsel yöntem"),
    (3, 4, 4, "Teknolojiyi bilinçli kullanmak ne demektir?", ["Gerektiği kadar ve amacına uygun kullanmak", "Hiç kullanmamak", "Sürekli kullanmak", "Rastgele kullanmak"], 0, "Ölçülü kullanım"),
    (4, 4, 4, "Bir buluşun topluma faydası nasıl ölçülür?", ["Hayatı ne kadar kolaylaştırdığıyla", "Fiyatıyla", "Boyutuyla", "Rengiyle"], 0, "Toplumsal fayda"),
]

# ==================================================== EKONOMI VE MESLEKLER

EKONOMI = [
    (1, 4, 4, "Üretim ne demektir?", ["Mal veya hizmet oluşturmak", "Satın almak", "Tüketmek", "Saklamak"], 0, "Üretim"),
    (1, 4, 4, "Tüketim ne demektir?", ["Mal ve hizmetleri kullanmak", "Üretmek", "Satmak", "Saklamak"], 0, "Tüketim"),
    (1, 4, 4, "Çiftçi ne üretir?", ["Tarım ürünleri", "Araba", "Kitap", "Bilgisayar"], 0, "Tarım ürünleri"),
    (1, 4, 4, "Hangisi bir meslektir?", ["Öğretmen", "Kitap", "Masa", "Kalem"], 0, "Öğretmenlik meslektir"),
    (2, 4, 4, "İhtiyaç ile istek arasındaki fark nedir?", ["İhtiyaç zorunlu, istek zorunlu değil", "Aynıdır", "İstek zorunlu", "Fark yoktur"], 0, "Zorunluluk farkı"),
    (2, 4, 4, "Hangisi temel ihtiyaçtır?", ["Beslenme", "Oyuncak", "Tatil", "Süs eşyası"], 0, "Beslenme, barınma, giyinme"),
    (2, 4, 4, "Bütçe ne demektir?", ["Gelir ve gider planı", "Para", "Alışveriş", "Tasarruf"], 0, "Planlama"),
    (2, 4, 4, "Tasarruf ne demektir?", ["Kaynakları bilinçli kullanmak", "Hiç harcamamak", "Çok harcamak", "Biriktirmemek"], 0, "Bilinçli kullanım"),
    (3, 4, 4, "Dağıtım ne demektir?", ["Ürünün üreticiden tüketiciye ulaşması", "Üretim", "Tüketim", "Saklama"], 0, "Lojistik zincir"),
    (3, 4, 4, "Meslek seçerken neye dikkat etmeliyiz?", ["İlgi ve yeteneklerimize", "Sadece paraya", "Arkadaşımıza", "Rastgele"], 0, "İlgi + yetenek"),
    (3, 4, 4, "Hangisi hizmet sektöründedir?", ["Doktor", "Çiftçi", "Madenci", "Balıkçı"], 0, "Doktorluk hizmettir"),
    (3, 4, 4, "Bilinçli tüketici ne yapar?", ["İhtiyacına göre alışveriş yapar", "Her şeyi alır", "Hiç almaz", "Reklamlara uyar"], 0, "Bilinçli tüketim"),
    (4, 4, 4, "Fiş veya fatura neden alınır?", ["Tüketici hakkı ve kayıt için", "Süs için", "Gereksizdir", "Zorunlu olduğu için sadece"], 0, "Tüketici hakları"),
    (4, 4, 4, "Arz ve talep ne demektir?", ["Sunulan ve istenen miktar", "Fiyat", "Kalite", "Marka"], 0, "Piyasa dengesi"),
    (5, 4, 4, "Ekonomik faaliyetler nasıl sıralanır?", ["Üretim, dağıtım, tüketim", "Tüketim, üretim, dağıtım", "Dağıtım, tüketim, üretim", "Rastgele"], 0, "Ekonomik döngü"),
    (1, 4, 4, "Doktor hangi meslek grubundadır?", ["Sağlık", "Tarım", "Sanayi", "İnşaat"], 0, "Sağlık mesleği"),
    (1, 4, 4, "Ekmek hangi meslek sayesinde üretilir?", ["Fırıncı", "Doktor", "Öğretmen", "Şoför"], 0, "Fırıncılık"),
    (1, 4, 4, "Para ne işe yarar?", ["Alışverişte kullanılır", "Süs", "Oyuncak", "Yiyecek"], 0, "Değişim aracı"),
    (2, 4, 4, "Hangisi tarım ürünüdür?", ["Buğday", "Otomobil", "Bilgisayar", "Telefon"], 0, "Tarım ürünü"),
    (2, 4, 4, "Hangisi sanayi ürünüdür?", ["Otomobil", "Domates", "Buğday", "Elma"], 0, "Fabrikada üretilir"),
    (2, 4, 4, "İthalat ne demektir?", ["Yurt dışından mal almak", "Yurt dışına satmak", "Üretmek", "Tüketmek"], 0, "Dışarıdan alım"),
    (2, 4, 4, "İhracat ne demektir?", ["Yurt dışına mal satmak", "Yurt dışından almak", "Üretmek", "Saklamak"], 0, "Dışarıya satış"),
    (3, 4, 4, "Meslekler neden çeşitlidir?", ["Toplumun farklı ihtiyaçları vardır", "Rastgele", "Zorunlu", "Eğlence için"], 0, "İhtiyaç çeşitliliği"),
    (3, 4, 4, "Alışverişte fiyat karşılaştırmak neden önemlidir?", ["Bilinçli tüketim için", "Zaman geçirmek için", "Gereksizdir", "Zorunlu"], 0, "Bilinçli tüketici"),
    (3, 4, 4, "Reklamlar bizi nasıl etkiler?", ["İhtiyacımız olmayan şeyi aldırabilir", "Hiç etkilemez", "Sadece bilgilendirir", "Ucuzlatır"], 0, "Bilinçli olmak gerekir"),
    (4, 4, 4, "Tüketici hakları neyi korur?", ["Alışverişte tüketiciyi", "Satıcıyı", "Üreticiyi", "Devleti"], 0, "Tüketicinin korunması"),
]

# ==================================================== VATANDASLIK

VATANDASLIK = [
    (1, 4, 4, "Vatandaş ne demektir?", ["Bir ülkenin üyesi olan kişi", "Turist", "Misafir", "Yabancı"], 0, "Ülke üyeliği"),
    (1, 4, 4, "Hangisi vatandaşlık görevidir?", ["Kurallara uymak", "Kural tanımamak", "Vergi kaçırmak", "Çevreyi kirletmek"], 0, "Kurallara uyum"),
    (1, 4, 4, "Oy vermek ne demektir?", ["Seçimde tercih belirtmek", "Para vermek", "Yardım etmek", "İzlemek"], 0, "Seçme hakkı"),
    (2, 4, 4, "Demokrasi ne demektir?", ["Halkın yönetimde söz sahibi olması", "Tek kişi yönetimi", "Askeri yönetim", "Kuralsızlık"], 0, "Halk egemenliği"),
    (2, 4, 4, "Kaç yaşında oy kullanılır?", ["18", "16", "20", "21"], 0, "18 yaş"),
    (2, 4, 4, "Vergi ne işe yarar?", ["Kamu hizmetleri finanse edilir", "Devlet zengin olur", "Gereksizdir", "Ceza olur"], 0, "Okul, hastane, yol vb."),
    (2, 4, 4, "Hangisi kamu hizmetidir?", ["Devlet hastanesi", "Market", "Kafe", "Sinema"], 0, "Kamu hizmeti"),
    (3, 4, 4, "Sivil toplum kuruluşu nedir?", ["Gönüllülerin kurduğu yardım kuruluşu", "Devlet dairesi", "Şirket", "Okul"], 0, "STK — gönüllü örgütlenme"),
    (3, 4, 4, "Etkin vatandaş ne yapar?", ["Toplumsal sorunlara duyarlıdır", "İlgilenmez", "İzler", "Şikayet eder sadece"], 0, "Aktif katılım"),
    (3, 4, 4, "Anayasa nedir?", ["Devletin temel kanunu", "Bir kitap", "Sözlük", "Harita"], 0, "En üst hukuk metni"),
    (3, 4, 4, "Kamu malına nasıl davranmalıyız?", ["Korumalıyız, hepimizindir", "İstediğimizi yapmalıyız", "Zarar verebiliriz", "İlgilenmemeliyiz"], 0, "Ortak mal bilinci"),
    (4, 4, 4, "Seçimlerde gizli oy neden önemlidir?", ["Özgür tercih için", "Gereksizdir", "Zorunlu olduğu için", "Hızlı olsun diye"], 0, "Baskısız tercih"),
    (4, 4, 4, "Toplumsal dayanışma ne demektir?", ["Zor durumda birbirine destek olmak", "Yalnız yaşamak", "Rekabet", "İlgisizlik"], 0, "Dayanışma"),
    (5, 4, 4, "Hukuk devleti ne demektir?", ["Herkesin kanunlara tabi olduğu devlet", "Kuralsız devlet", "Tek kişilik yönetim", "Askeri yönetim"], 0, "Kanun önünde eşitlik"),
    (1, 4, 4, "Trafik kurallarına kim uymalıdır?", ["Herkes", "Sadece sürücüler", "Sadece yayalar", "Kimse"], 0, "Herkes"),
    (1, 4, 4, "Hangisi iyi bir vatandaş davranışıdır?", ["Çevreyi temiz tutmak", "Çöp atmak", "Gürültü yapmak", "Kurallara uymamak"], 0, "Çevre bilinci"),
    (1, 4, 4, "Bayrağımıza nasıl davranmalıyız?", ["Saygı göstermeliyiz", "İlgilenmemeliyiz", "Yere atmalıyız", "Kirletmeliyiz"], 0, "Milli değer"),
    (2, 4, 4, "Belediye ne iş yapar?", ["Şehrin hizmetlerini yürütür", "Ders verir", "Tedavi eder", "Ürün satar"], 0, "Yerel yönetim"),
    (2, 4, 4, "Muhtar nasıl göreve gelir?", ["Seçimle", "Atamayla", "Kurayla", "Sırayla"], 0, "Halk seçer"),
    (2, 4, 4, "Hangisi kamu malıdır?", ["Park", "Evimiz", "Çantamız", "Bisikletimiz"], 0, "Ortak kullanım alanı"),
    (3, 4, 4, "Gönüllülük ne demektir?", ["Karşılık beklemeden yardım etmek", "Ücretle çalışmak", "Zorunlu görev", "İzlemek"], 0, "Gönüllü katılım"),
    (3, 4, 4, "Toplumsal sorunlara duyarlı olmak ne demektir?", ["Fark etmek ve çözüme katkı sunmak", "Görmezden gelmek", "Şikayet etmek", "Beklemek"], 0, "Duyarlı vatandaşlık"),
    (3, 4, 4, "Kanunlar neden vardır?", ["Toplumsal düzeni sağlamak için", "Cezalandırmak için", "Zorlaştırmak için", "Gereksizdir"], 0, "Düzen ve adalet"),
    (4, 4, 4, "Katılımcı demokrasi ne demektir?", ["Vatandaşların karar süreçlerine katılması", "Sadece oy vermek", "İzlemek", "Karışmamak"], 0, "Aktif katılım"),
    (4, 4, 4, "Dilekçe hakkı ne demektir?", ["Yetkililere yazılı başvuru yapabilmek", "Şikayet etmek", "Konuşmak", "Oy vermek"], 0, "Anayasal hak"),
]

# ==================================================== DUNYA ULKELERI

DUNYA_ULKELERI = [
    (1, 4, 4, "Bu bayrak hangi ülkeye aittir?\n\n🇩🇪", ["Almanya", "Fransa", "İtalya", "Belçika"], 0, "Almanya"),
    (1, 4, 4, "Bu bayrak hangi ülkeye aittir?\n\n🇫🇷", ["Fransa", "Almanya", "İtalya", "Hollanda"], 0, "Fransa"),
    (1, 4, 4, "Bu bayrak hangi ülkeye aittir?\n\n🇯🇵", ["Japonya", "Çin", "Kore", "Vietnam"], 0, "Japonya"),
    (1, 4, 4, "Dünyada kaç kıta vardır?", ["7", "5", "6", "8"], 0, "7 kıta"),
    (2, 4, 4, "Almanya'nın başkenti neresidir?", ["Berlin", "Münih", "Hamburg", "Frankfurt"], 0, "Berlin"),
    (2, 4, 4, "Fransa'nın başkenti neresidir?", ["Paris", "Lyon", "Marsilya", "Nice"], 0, "Paris"),
    (2, 4, 4, "Japonya'nın başkenti neresidir?", ["Tokyo", "Osaka", "Kyoto", "Nagoya"], 0, "Tokyo"),
    (2, 4, 4, "En kalabalık kıta hangisidir?", ["Asya", "Afrika", "Avrupa", "Amerika"], 0, "Asya"),
    (2, 4, 4, "Türkiye'nin komşusu hangisidir?", ["Bulgaristan", "Almanya", "Mısır", "İtalya"], 0, "Kara komşusu"),
    (3, 4, 4, "İngiltere'nin başkenti neresidir?", ["Londra", "Manchester", "Liverpool", "Oxford"], 0, "Londra"),
    (3, 4, 4, "En büyük okyanus hangisidir?", ["Büyük Okyanus", "Atlas Okyanusu", "Hint Okyanusu", "Kuzey Buz"], 0, "Pasifik (Büyük) Okyanus"),
    (3, 4, 4, "Hangi kıtada insan yaşamaz?", ["Antarktika", "Afrika", "Asya", "Avrupa"], 0, "Antarktika (kalıcı yerleşim yok)"),
    (3, 4, 4, "Birleşmiş Milletler ne yapar?", ["Ülkeler arası barış ve iş birliği sağlar", "Savaş açar", "Ticaret yapar", "Spor düzenler"], 0, "BM"),
    (4, 4, 4, "Küresel ısınma neden dünya sorunudur?", ["Tüm ülkeleri etkiler", "Sadece bir ülkeyi", "Etkisi yok", "Sadece kutupları"], 0, "Ortak sorun"),
    (4, 4, 4, "Ülkeler arasında iş birliği neden gereklidir?", ["Ortak sorunları çözmek için", "Gereksizdir", "Rekabet için", "Savaş için"], 0, "Küresel sorunlar"),
    (5, 4, 4, "Kültürel etkileşim ne demektir?", ["Toplumların birbirinden etkilenmesi", "Kültürün yok olması", "Tek kültür", "İzolasyon"], 0, "Karşılıklı etkileşim"),
    (1, 4, 4, "Bu bayrak hangi ülkeye aittir?\n\n🇮🇹", ["İtalya", "Fransa", "İrlanda", "Meksika"], 0, "İtalya"),
    (1, 4, 4, "Bu bayrak hangi ülkeye aittir?\n\n🇬🇧", ["İngiltere", "Fransa", "Almanya", "Hollanda"], 0, "Birleşik Krallık"),
    (1, 4, 4, "Bu bayrak hangi ülkeye aittir?\n\n🇺🇸", ["ABD", "İngiltere", "Kanada", "Avustralya"], 0, "Amerika Birleşik Devletleri"),
    (2, 4, 4, "İtalya'nın başkenti neresidir?", ["Roma", "Milano", "Venedik", "Napoli"], 0, "Roma"),
    (2, 4, 4, "En büyük kıta hangisidir?", ["Asya", "Afrika", "Avrupa", "Amerika"], 0, "Asya"),
    (2, 4, 4, "Ekvator neyi ikiye böler?", ["Dünyayı kuzey ve güney olarak", "Kıtaları", "Okyanusları", "Ülkeleri"], 0, "Kuzey ve Güney Yarım Küre"),
    (3, 4, 4, "Hangi ülke hem Asya hem Avrupa'dadır?", ["Türkiye", "Almanya", "Mısır", "Japonya"], 0, "Türkiye iki kıtada"),
    (3, 4, 4, "Nüfusu en fazla olan ülkelerden biri hangisidir?", ["Çin", "Türkiye", "İsviçre", "Norveç"], 0, "Çin ve Hindistan"),
    (3, 4, 4, "UNESCO ne yapar?", ["Eğitim, bilim ve kültürü destekler", "Savaş yönetir", "Ticaret yapar", "Spor düzenler"], 0, "BM kuruluşu"),
    (4, 4, 4, "Ülkeler arasındaki sınırlar neyi belirler?", ["Ülkelerin egemenlik alanını", "İklimi", "Dili", "Dini"], 0, "Egemenlik sınırı"),
]
