"""
Turkce yazili soru bankasi. 1-2. sinif.
Format: (band, sinif_min, sinif_max, soru, [siklar], dogru_index, aciklama)
"""

# ---------------------------------------------------------------- ES ANLAMLI

ES_ANLAMLI = [
    (1, 2, 4, '"Okul" kelimesinin eş anlamlısı hangisidir?', ["Mektep", "Sınıf", "Öğretmen", "Kitap"], 0, "Okul = Mektep"),
    (1, 2, 4, '"Kırmızı" kelimesinin eş anlamlısı hangisidir?', ["Al", "Mavi", "Sarı", "Yeşil"], 0, "Kırmızı = Al"),
    (1, 2, 4, '"Siyah" kelimesinin eş anlamlısı hangisidir?', ["Kara", "Beyaz", "Gri", "Mor"], 0, "Siyah = Kara"),
    (1, 2, 4, '"Beyaz" kelimesinin eş anlamlısı hangisidir?', ["Ak", "Kara", "Sarı", "Pembe"], 0, "Beyaz = Ak"),
    (1, 2, 4, '"Ev" kelimesinin eş anlamlısı hangisidir?', ["Konut", "Bahçe", "Sokak", "Kapı"], 0, "Ev = Konut"),
    (1, 2, 4, '"Doktor" kelimesinin eş anlamlısı hangisidir?', ["Hekim", "Hemşire", "Hasta", "İlaç"], 0, "Doktor = Hekim"),
    (1, 2, 4, '"Hediye" kelimesinin eş anlamlısı hangisidir?', ["Armağan", "Oyuncak", "Paket", "Kutu"], 0, "Hediye = Armağan"),
    (2, 2, 4, '"Cevap" kelimesinin eş anlamlısı hangisidir?', ["Yanıt", "Soru", "Sınav", "Konu"], 0, "Cevap = Yanıt"),
    (2, 2, 4, '"Misafir" kelimesinin eş anlamlısı hangisidir?', ["Konuk", "Komşu", "Arkadaş", "Akraba"], 0, "Misafir = Konuk"),
    (2, 2, 4, '"Yıl" kelimesinin eş anlamlısı hangisidir?', ["Sene", "Ay", "Hafta", "Gün"], 0, "Yıl = Sene"),
    (2, 2, 4, '"Sınıf" kelimesinin eş anlamlısı hangisidir?', ["Derslik", "Okul", "Bahçe", "Koridor"], 0, "Sınıf = Derslik"),
    (2, 2, 4, '"Hikâye" kelimesinin eş anlamlısı hangisidir?', ["Öykü", "Şiir", "Roman", "Masal"], 0, "Hikâye = Öykü"),
    (2, 2, 4, '"Vatan" kelimesinin eş anlamlısı hangisidir?', ["Yurt", "Şehir", "Köy", "Ülke"], 0, "Vatan = Yurt"),
    (2, 2, 4, '"Kelime" kelimesinin eş anlamlısı hangisidir?', ["Sözcük", "Harf", "Cümle", "Hece"], 0, "Kelime = Sözcük"),
    (2, 2, 4, '"Öğretmen" kelimesinin eş anlamlısı hangisidir?', ["Muallim", "Öğrenci", "Müdür", "Veli"], 0, "Öğretmen = Muallim"),
    (2, 2, 4, '"Hasta" kelimesinin eş anlamlısı hangisidir?', ["Rahatsız", "Sağlıklı", "Güçlü", "Mutlu"], 0, "Hasta = Rahatsız"),
    (2, 2, 4, '"Zengin" kelimesinin eş anlamlısı hangisidir?', ["Varlıklı", "Fakir", "Cimri", "Cömert"], 0, "Zengin = Varlıklı"),
    (2, 2, 4, '"Fakir" kelimesinin eş anlamlısı hangisidir?', ["Yoksul", "Zengin", "Varlıklı", "Mutlu"], 0, "Fakir = Yoksul"),
    (3, 2, 4, '"Ihtiyar" kelimesinin eş anlamlısı hangisidir?', ["Yaşlı", "Genç", "Çocuk", "Bebek"], 0, "İhtiyar = Yaşlı"),
    (3, 2, 4, '"Sadece" kelimesinin eş anlamlısı hangisidir?', ["Yalnızca", "Hepsi", "Bazen", "Çoğu"], 0, "Sadece = Yalnızca"),
    (3, 2, 4, '"Yaklaşık" kelimesinin eş anlamlısı hangisidir?', ["Tahminen", "Kesin", "Tam", "Doğru"], 0, "Yaklaşık = Tahminen"),
    (3, 2, 4, '"Meşgul" kelimesinin eş anlamlısı hangisidir?', ["Yoğun", "Boş", "Serbest", "Tembel"], 0, "Meşgul = Yoğun"),
    (3, 2, 4, '"Neşeli" kelimesinin eş anlamlısı hangisidir?', ["Sevinçli", "Üzgün", "Kızgın", "Yorgun"], 0, "Neşeli = Sevinçli"),
    (3, 2, 4, '"Cesur" kelimesinin eş anlamlısı hangisidir?', ["Yiğit", "Korkak", "Utangaç", "Sessiz"], 0, "Cesur = Yiğit"),
    (3, 3, 4, '"Mütevazı" kelimesinin eş anlamlısı hangisidir?', ["Alçakgönüllü", "Kibirli", "Gururlu", "Cesur"], 0, "Mütevazı = Alçakgönüllü"),
    (3, 2, 4, '"Bina" kelimesinin eş anlamlısı hangisidir?', ["Yapı", "Sokak", "Bahçe", "Oda"], 0, "Bina = Yapı"),
    (3, 2, 4, '"Ünlü" kelimesinin eş anlamlısı hangisidir?', ["Meşhur", "Bilinmeyen", "Gizli", "Sıradan"], 0, "Ünlü = Meşhur"),
    (3, 2, 4, '"Sıcak" kelimesinin eş anlamlısı hangisidir?', ["Kızgın", "Soğuk", "Serin", "Ilık"], 0, "Sıcak = Kızgın (hava için)"),
    (4, 3, 4, '"Kâinat" kelimesinin eş anlamlısı hangisidir?', ["Evren", "Dünya", "Gezegen", "Yıldız"], 0, "Kâinat = Evren"),
    (4, 3, 4, '"Muhabbet" kelimesinin eş anlamlısı hangisidir?', ["Sevgi", "Nefret", "Öfke", "Korku"], 0, "Muhabbet = Sevgi"),
    (4, 3, 4, '"Tabiat" kelimesinin eş anlamlısı hangisidir?', ["Doğa", "Şehir", "Bina", "Yol"], 0, "Tabiat = Doğa"),
    (4, 3, 4, '"Hürriyet" kelimesinin eş anlamlısı hangisidir?', ["Özgürlük", "Esaret", "Tutsaklık", "Bağlılık"], 0, "Hürriyet = Özgürlük"),
    (4, 3, 4, '"Mesafe" kelimesinin eş anlamlısı hangisidir?', ["Uzaklık", "Yakınlık", "Genişlik", "Derinlik"], 0, "Mesafe = Uzaklık"),
    (4, 3, 4, '"Şuur" kelimesinin eş anlamlısı hangisidir?', ["Bilinç", "Uyku", "Rüya", "Hayal"], 0, "Şuur = Bilinç"),
    (5, 3, 4, '"Bilhassa" kelimesinin eş anlamlısı hangisidir?', ["Özellikle", "Genellikle", "Bazen", "Asla"], 0, "Bilhassa = Özellikle"),
    (5, 3, 4, '"Nadiren" kelimesinin eş anlamlısı hangisidir?', ["Seyrek", "Sık sık", "Her zaman", "Daima"], 0, "Nadiren = Seyrek"),
    (5, 3, 4, '"Mahzun" kelimesinin eş anlamlısı hangisidir?', ["Üzgün", "Neşeli", "Kızgın", "Şaşkın"], 0, "Mahzun = Üzgün"),
    (5, 3, 4, '"İtina" kelimesinin eş anlamlısı hangisidir?', ["Özen", "Acele", "Tembellik", "İhmal"], 0, "İtina = Özen"),
]

# ---------------------------------------------------------------- ZIT ANLAMLI

ZIT_ANLAMLI = [
    (1, 2, 4, '"Büyük" kelimesinin zıt anlamlısı hangisidir?', ["Küçük", "Uzun", "Geniş", "Kalın"], 0, "Büyük ↔ Küçük"),
    (1, 2, 4, '"Uzun" kelimesinin zıt anlamlısı hangisidir?', ["Kısa", "Küçük", "İnce", "Dar"], 0, "Uzun ↔ Kısa"),
    (1, 2, 4, '"Sıcak" kelimesinin zıt anlamlısı hangisidir?', ["Soğuk", "Ilık", "Serin", "Yumuşak"], 0, "Sıcak ↔ Soğuk"),
    (1, 2, 4, '"Açık" kelimesinin zıt anlamlısı hangisidir?', ["Kapalı", "Geniş", "Büyük", "Yeni"], 0, "Açık ↔ Kapalı"),
    (1, 2, 4, '"Gece" kelimesinin zıt anlamlısı hangisidir?', ["Gündüz", "Akşam", "Sabah", "Öğle"], 0, "Gece ↔ Gündüz"),
    (1, 2, 4, '"Yaşlı" kelimesinin zıt anlamlısı hangisidir?', ["Genç", "İhtiyar", "Büyük", "Uzun"], 0, "Yaşlı ↔ Genç"),
    (1, 2, 4, '"Beyaz" kelimesinin zıt anlamlısı hangisidir?', ["Siyah", "Gri", "Mavi", "Sarı"], 0, "Beyaz ↔ Siyah"),
    (1, 2, 4, '"Aşağı" kelimesinin zıt anlamlısı hangisidir?', ["Yukarı", "İleri", "Geri", "Yan"], 0, "Aşağı ↔ Yukarı"),
    (2, 2, 4, '"Kalın" kelimesinin zıt anlamlısı hangisidir?', ["İnce", "Kısa", "Küçük", "Dar"], 0, "Kalın ↔ İnce"),
    (2, 2, 4, '"Hızlı" kelimesinin zıt anlamlısı hangisidir?', ["Yavaş", "Çabuk", "Acele", "Ani"], 0, "Hızlı ↔ Yavaş"),
    (2, 2, 4, '"Temiz" kelimesinin zıt anlamlısı hangisidir?', ["Kirli", "Düzenli", "Parlak", "Yeni"], 0, "Temiz ↔ Kirli"),
    (2, 2, 4, '"Dolu" kelimesinin zıt anlamlısı hangisidir?', ["Boş", "Ağır", "Büyük", "Geniş"], 0, "Dolu ↔ Boş"),
    (2, 2, 4, '"Ağır" kelimesinin zıt anlamlısı hangisidir?', ["Hafif", "Büyük", "Kalın", "Sert"], 0, "Ağır ↔ Hafif"),
    (2, 2, 4, '"Zengin" kelimesinin zıt anlamlısı hangisidir?', ["Fakir", "Cimri", "Cömert", "Mutlu"], 0, "Zengin ↔ Fakir"),
    (2, 2, 4, '"Mutlu" kelimesinin zıt anlamlısı hangisidir?', ["Üzgün", "Neşeli", "Sevinçli", "Şen"], 0, "Mutlu ↔ Üzgün"),
    (2, 2, 4, '"İleri" kelimesinin zıt anlamlısı hangisidir?', ["Geri", "Yukarı", "Aşağı", "Yan"], 0, "İleri ↔ Geri"),
    (2, 2, 4, '"Yeni" kelimesinin zıt anlamlısı hangisidir?', ["Eski", "Temiz", "Güzel", "Büyük"], 0, "Yeni ↔ Eski"),
    (2, 2, 4, '"Güzel" kelimesinin zıt anlamlısı hangisidir?', ["Çirkin", "Hoş", "Şirin", "Tatlı"], 0, "Güzel ↔ Çirkin"),
    (3, 2, 4, '"Cesur" kelimesinin zıt anlamlısı hangisidir?', ["Korkak", "Yiğit", "Güçlü", "Kahraman"], 0, "Cesur ↔ Korkak"),
    (3, 2, 4, '"Kolay" kelimesinin zıt anlamlısı hangisidir?', ["Zor", "Basit", "Sade", "Hafif"], 0, "Kolay ↔ Zor"),
    (3, 2, 4, '"Doğru" kelimesinin zıt anlamlısı hangisidir?', ["Yanlış", "Kesin", "Net", "Açık"], 0, "Doğru ↔ Yanlış"),
    (3, 2, 4, '"Cömert" kelimesinin zıt anlamlısı hangisidir?', ["Cimri", "Zengin", "İyi", "Nazik"], 0, "Cömert ↔ Cimri"),
    (3, 2, 4, '"Sessiz" kelimesinin zıt anlamlısı hangisidir?', ["Gürültülü", "Sakin", "Yavaş", "Uslu"], 0, "Sessiz ↔ Gürültülü"),
    (3, 2, 4, '"Uzak" kelimesinin zıt anlamlısı hangisidir?', ["Yakın", "Geniş", "Büyük", "Derin"], 0, "Uzak ↔ Yakın"),
    (3, 2, 4, '"Sert" kelimesinin zıt anlamlısı hangisidir?', ["Yumuşak", "Ağır", "Kalın", "Güçlü"], 0, "Sert ↔ Yumuşak"),
    (3, 2, 4, '"Bol" kelimesinin zıt anlamlısı hangisidir?', ["Az", "Çok", "Geniş", "Dolu"], 0, "Bol ↔ Az"),
    (4, 3, 4, '"Tembel" kelimesinin zıt anlamlısı hangisidir?', ["Çalışkan", "Yorgun", "Uykulu", "Yavaş"], 0, "Tembel ↔ Çalışkan"),
    (4, 3, 4, '"Cömertlik" kelimesinin zıt anlamlısı hangisidir?', ["Cimrilik", "İyilik", "Nezaket", "Dostluk"], 0, "Cömertlik ↔ Cimrilik"),
    (4, 3, 4, '"Savaş" kelimesinin zıt anlamlısı hangisidir?', ["Barış", "Kavga", "Çatışma", "Mücadele"], 0, "Savaş ↔ Barış"),
    (4, 3, 4, '"Ucuz" kelimesinin zıt anlamlısı hangisidir?', ["Pahalı", "Değerli", "Kaliteli", "Yeni"], 0, "Ucuz ↔ Pahalı"),
    (4, 3, 4, '"Dost" kelimesinin zıt anlamlısı hangisidir?', ["Düşman", "Arkadaş", "Komşu", "Tanıdık"], 0, "Dost ↔ Düşman"),
    (4, 3, 4, '"Alçak" kelimesinin zıt anlamlısı hangisidir?', ["Yüksek", "Derin", "Geniş", "Uzun"], 0, "Alçak ↔ Yüksek"),
    (5, 3, 4, '"İyimser" kelimesinin zıt anlamlısı hangisidir?', ["Kötümser", "Neşeli", "Mutlu", "Umutlu"], 0, "İyimser ↔ Kötümser"),
    (5, 3, 4, '"Bilgili" kelimesinin zıt anlamlısı hangisidir?', ["Cahil", "Akıllı", "Zeki", "Çalışkan"], 0, "Bilgili ↔ Cahil"),
    (5, 3, 4, '"Sabırlı" kelimesinin zıt anlamlısı hangisidir?', ["Aceleci", "Sakin", "Uslu", "Yavaş"], 0, "Sabırlı ↔ Aceleci"),
    (5, 3, 4, '"Geçici" kelimesinin zıt anlamlısı hangisidir?', ["Kalıcı", "Kısa", "Hızlı", "Ani"], 0, "Geçici ↔ Kalıcı"),
]

# ---------------------------------------------------------------- DOGRU YAZILIS

DOGRU_YAZILIS = [
    (1, 1, 4, "Hangisi doğru yazılmıştır?", ["kitap", "kitab", "gitap", "kittap"], 0, "kitap"),
    (1, 1, 4, "Hangisi doğru yazılmıştır?", ["kalem", "kalam", "galem", "kelem"], 0, "kalem"),
    (1, 1, 4, "Hangisi doğru yazılmıştır?", ["okul", "ogul", "okulll", "oukl"], 0, "okul"),
    (1, 1, 4, "Hangisi doğru yazılmıştır?", ["araba", "arraba", "arabba", "erebe"], 0, "araba"),
    (1, 1, 4, "Hangisi doğru yazılmıştır?", ["elma", "alma", "elmma", "ellma"], 0, "elma"),
    (1, 1, 4, "Hangisi doğru yazılmıştır?", ["çiçek", "çicek", "cicek", "çiçekk"], 0, "çiçek"),
    (2, 1, 4, "Hangisi doğru yazılmıştır?", ["ağaç", "agaç", "ağac", "aağç"], 0, "ağaç"),
    (2, 1, 4, "Hangisi doğru yazılmıştır?", ["yalnız", "yanlız", "yalnuz", "yalnızz"], 0, "yalnız (tek başına)"),
    (2, 2, 4, "Hangisi doğru yazılmıştır?", ["herkes", "herkez", "herkeş", "herkess"], 0, "herkes"),
    (2, 2, 4, "Hangisi doğru yazılmıştır?", ["yanlış", "yalnış", "yanliş", "yannış"], 0, "yanlış (hatalı)"),
    (2, 2, 4, "Hangisi doğru yazılmıştır?", ["şoför", "şöför", "shoför", "soför"], 0, "şoför"),
    (2, 2, 4, "Hangisi doğru yazılmıştır?", ["kirpi", "kirpı", "kırpi", "kirppi"], 0, "kirpi"),
    (2, 1, 4, "Hangisi doğru yazılmıştır?", ["gözlük", "gözluk", "gözlükk", "gözlik"], 0, "gözlük"),
    (2, 1, 4, "Hangisi doğru yazılmıştır?", ["öğretmen", "ögretmen", "öğretman", "öretmen"], 0, "öğretmen"),
    (3, 2, 4, "Hangisi doğru yazılmıştır?", ["kitapçı", "kitapci", "kitabçı", "kitapçi"], 0, "kitapçı"),
    (3, 2, 4, "Hangisi doğru yazılmıştır?", ["ilkokul", "ilk okul", "ilkokull", "ilokul"], 0, "ilkokul (bitişik)"),
    (3, 2, 4, "Hangisi doğru yazılmıştır?", ["birçok", "bir çok", "birçokk", "bircok"], 0, "birçok (bitişik)"),
    (3, 2, 4, "Hangisi doğru yazılmıştır?", ["her gün", "hergün", "hergun", "her günn"], 0, "her gün (ayrı)"),
    (3, 2, 4, "Hangisi doğru yazılmıştır?", ["hiçbir", "hiç bir", "hicbir", "hiçbirr"], 0, "hiçbir (bitişik)"),
    (3, 2, 4, "Hangisi doğru yazılmıştır?", ["bir şey", "birşey", "birşeyy", "bir sey"], 0, "bir şey (ayrı)"),
    (3, 2, 4, "Hangisi doğru yazılmıştır?", ["yarın", "yarin", "yaarın", "yarınn"], 0, "yarın"),
    (3, 2, 4, "Hangisi doğru yazılmıştır?", ["makine", "makina", "makinne", "makkine"], 0, "makine"),
    (4, 2, 4, "Hangisi doğru yazılmıştır?", ["direksiyon", "direksyon", "direksiyoon", "direksion"], 0, "direksiyon"),
    (4, 2, 4, "Hangisi doğru yazılmıştır?", ["ambulans", "ambülans", "ambulanss", "anbulans"], 0, "ambulans"),
    (4, 2, 4, "Hangisi doğru yazılmıştır?", ["kravat", "karvat", "kıravat", "kravatt"], 0, "kravat"),
    (4, 3, 4, "Hangisi doğru yazılmıştır?", ["orijinal", "orjinal", "orijnal", "orjınal"], 0, "orijinal"),
    (4, 3, 4, "Hangisi doğru yazılmıştır?", ["laboratuvar", "laboratuar", "labaratuvar", "laboratvar"], 0, "laboratuvar"),
    (4, 3, 4, "Hangisi doğru yazılmıştır?", ["klavye", "klavya", "kılavye", "klavyye"], 0, "klavye"),
    (5, 3, 4, "Hangisi doğru yazılmıştır?", ["eşofman", "eşortman", "eşofmann", "eşoftman"], 0, "eşofman"),
    (5, 3, 4, "Hangisi doğru yazılmıştır?", ["sürpriz", "süpriz", "sürprizz", "sürperiz"], 0, "sürpriz"),
    (5, 3, 4, "Hangisi doğru yazılmıştır?", ["yanlışlıkla", "yalnışlıkla", "yanlişlikla", "yannışlıkla"], 0, "yanlışlıkla"),
    (5, 3, 4, "Hangisi doğru yazılmıştır?", ["dinlenmek", "dinlemek", "dinlenmeek", "dinnlenmek"], 0, "dinlenmek (istirahat)"),
]

# ---------------------------------------------------------------- NOKTALAMA

NOKTALAMA = [
    (1, 2, 4, "Cümlenin sonuna hangi işaret gelmeli?\n\nAli okula gitti __", [".", "?", "!", ","], 0, "Bildiren cümle → nokta"),
    (1, 2, 4, "Cümlenin sonuna hangi işaret gelmeli?\n\nAdın ne __", ["?", ".", "!", ","], 0, "Soru cümlesi → soru işareti"),
    (1, 2, 4, "Cümlenin sonuna hangi işaret gelmeli?\n\nAman dikkat et __", ["!", ".", "?", ","], 0, "Ünlem bildiren cümle → ünlem"),
    (1, 2, 4, "Cümlenin sonuna hangi işaret gelmeli?\n\nBugün hava çok güzel __", [".", "?", ",", ":"], 0, "Bildiren cümle → nokta"),
    (2, 2, 4, "Cümlenin sonuna hangi işaret gelmeli?\n\nKaç yaşındasın __", ["?", ".", "!", ";"], 0, "Soru cümlesi → soru işareti"),
    (2, 2, 4, "Cümlenin sonuna hangi işaret gelmeli?\n\nNe kadar güzel bir manzara __", ["!", ".", "?", ","], 0, "Şaşkınlık/hayranlık → ünlem"),
    (2, 2, 4, "Hangi cümlede noktalama doğru kullanılmıştır?", ["Bugün okula gittim.", "Bugün okula gittim?", "Bugün okula gittim,", "Bugün okula gittim"], 0, "Bildiren cümle noktayla biter"),
    (2, 2, 4, "Hangi cümlede noktalama doğru kullanılmıştır?", ["Nereye gidiyorsun?", "Nereye gidiyorsun.", "Nereye gidiyorsun!", "Nereye gidiyorsun,"], 0, "Soru cümlesi soru işaretiyle biter"),
    (3, 2, 4, "Boşluğa hangi işaret gelmeli?\n\nElma __ armut ve muz aldım.", [",", ".", "?", "!"], 0, "Sıralamada virgül kullanılır"),
    (3, 2, 4, "Boşluğa hangi işaret gelmeli?\n\nAli __ buraya gel!", [",", ".", "?", ":"], 0, "Hitaptan sonra virgül"),
    (3, 3, 4, "Hangi cümlede virgül doğru kullanılmıştır?", ["Kalem, defter ve silgi aldım.", "Kalem defter, ve silgi aldım.", "Kalem defter ve, silgi aldım.", "Kalem, defter, ve silgi aldım."], 0, "Sıralamada son öğeden önce 've' varsa virgül konmaz"),
    (3, 2, 4, "Hangisi soru cümlesidir?", ["Yarın gelecek misin?", "Yarın geleceğim.", "Yarın gel!", "Yarın hava güzel."], 0, "Soru anlamı taşıyan cümle"),
    (3, 2, 4, "Hangi cümlede ünlem kullanılmalı?", ["İmdat", "Bugün pazartesi", "Kitap okuyorum", "Adım Ali"], 0, "Seslenme/heyecan → ünlem"),
    (4, 3, 4, "Boşluğa hangi işaret gelmeli?\n\nAnnem __ \"Yemek hazır\" dedi.", [":", ",", ".", "?"], 0, "Konuşmadan önce iki nokta"),
    (4, 3, 4, "Hangi cümlede noktalama hatası vardır?", ["Ali, nereye gidiyorsun.", "Ali, nereye gidiyorsun?", "Ali okula gitti.", "Ne güzel bir gün!"], 0, "Soru cümlesi noktayla bitmez"),
    (4, 3, 4, "Kısaltmadan sonra hangi işaret kullanılır?\n\nDr __ Ahmet Bey geldi.", [".", ",", ":", "!"], 0, "Kısaltmadan sonra nokta: Dr."),
    (4, 3, 4, "Tarih yazarken hangi işaret kullanılır?\n\n29 Ekim 1923 __", [".", ",", ":", "-"], 0, "Tarih sonunda nokta"),
    (5, 3, 4, "Hangi cümlede tırnak işareti doğru kullanılmıştır?", ['Öğretmen "Sessiz olun" dedi.', 'Öğretmen Sessiz olun dedi.', 'Öğretmen: Sessiz olun dedi.', 'Öğretmen, "Sessiz olun dedi.'], 0, "Başkasının sözü tırnak içinde"),
    (5, 3, 4, "Hangisinde kesme işareti doğru kullanılmıştır?", ["Ankara'ya gittim.", "Ankaraya gittim.", "Ankara ya gittim.", "Ankara'ya' gittim."], 0, "Özel isme gelen ek kesme işaretiyle ayrılır"),
    (1, 2, 4, "Cümlenin sonuna hangi işaret gelmeli?\n\nKedim çok tatlı __", [".", "?", ",", ":"], 0, "Bildiren cümle → nokta"),
    (1, 2, 4, "Cümlenin sonuna hangi işaret gelmeli?\n\nBu kim __", ["?", ".", "!", ","], 0, "Soru cümlesi → soru işareti"),
    (2, 2, 4, "Cümlenin sonuna hangi işaret gelmeli?\n\nYaşasın, tatil geldi __", ["!", ".", "?", ","], 0, "Sevinç bildiren cümle → ünlem"),
    (2, 2, 4, "Hangi cümlede noktalama doğru kullanılmıştır?", ["Yarın sinemaya gideceğiz.", "Yarın sinemaya gideceğiz?", "Yarın sinemaya gideceğiz,", "Yarın sinemaya gideceğiz:"], 0, "Bildiren cümle noktayla biter"),
    (2, 2, 4, "Cümlenin sonuna hangi işaret gelmeli?\n\nSaat kaç __", ["?", ".", "!", ";"], 0, "Soru cümlesi → soru işareti"),
    (3, 2, 4, "Boşluğa hangi işaret gelmeli?\n\nAnne __ babam ve kardeşim geldi.", [",", ".", "?", "!"], 0, "Sıralamada virgül"),
    (3, 2, 4, "Hangisi ünlem cümlesidir?", ["Ne kadar soğuk!", "Bugün hava soğuk.", "Hava soğuk mu?", "Hava soğuyor."], 0, "Hayranlık/şaşkınlık → ünlem"),
    (3, 3, 4, "Boşluğa hangi işaret gelmeli?\n\nZeynep __ kapıyı kapatır mısın?", [",", ".", "!", ":"], 0, "Hitaptan sonra virgül"),
    (4, 3, 4, "Hangi cümlede noktalama hatası vardır?", ["Nereye gidiyorsun.", "Nereye gidiyorsun?", "Buraya gel!", "Eve gidiyorum."], 0, "Soru cümlesi soru işaretiyle biter"),
    (4, 3, 4, "Kısaltmadan sonra hangi işaret kullanılır?\n\nProf __ Dr. Ayşe Hanım", [".", ",", ":", "!"], 0, "Kısaltmadan sonra nokta"),
    (5, 3, 4, "Hangisinde kesme işareti doğru kullanılmıştır?", ["Atatürk'ün sözleri", "Atatürkün sözleri", "Atatürk ün sözleri", "Atatürk'ün' sözleri"], 0, "Özel isme gelen ek kesme işaretiyle ayrılır"),
    (5, 3, 4, "Boşluğa hangi işaret gelmeli?\n\nAlışveriş listesi __ ekmek, süt, peynir", [":", ",", ".", "?"], 0, "Açıklama öncesi iki nokta"),
]
