"""
Geometri (matematik) + Ingilizce yazili soru bankasi.
Format: (band, sinif_min, sinif_max, soru, [siklar], dogru_index, aciklama)
"""

# ---------------------------------------------------------------- GEOMETRI

GEOMETRI = [
    (1, 1, 4, "Bu şekil nedir?\n\n⬛", ["Kare", "Üçgen", "Daire", "Dikdörtgen"], 0, "Kare"),
    (1, 1, 4, "Bu şekil nedir?\n\n🔺", ["Üçgen", "Kare", "Daire", "Dikdörtgen"], 0, "Üçgen"),
    (1, 1, 4, "Bu şekil nedir?\n\n⚫", ["Daire", "Kare", "Üçgen", "Dikdörtgen"], 0, "Daire"),
    (1, 1, 4, "Üçgenin kaç kenarı vardır?", ["3", "4", "5", "6"], 0, "Üçgen: 3 kenar"),
    (1, 1, 4, "Karenin kaç kenarı vardır?", ["4", "3", "5", "6"], 0, "Kare: 4 kenar"),
    (1, 1, 4, "Dairenin kaç köşesi vardır?", ["0", "1", "2", "4"], 0, "Dairenin köşesi yoktur"),
    (2, 1, 4, "Üçgenin kaç köşesi vardır?", ["3", "4", "0", "6"], 0, "Üçgen: 3 köşe"),
    (2, 1, 4, "Karenin kaç köşesi vardır?", ["4", "3", "5", "0"], 0, "Kare: 4 köşe"),
    (2, 1, 4, "Hangisinin köşesi yoktur?", ["Daire", "Kare", "Üçgen", "Dikdörtgen"], 0, "Daire yuvarlaktır"),
    (2, 2, 4, "Karenin kenarları nasıldır?", ["Hepsi eşit", "Farklı", "İkisi eşit", "Hiçbiri eşit değil"], 0, "Karenin 4 kenarı eşittir"),
    (2, 2, 4, "Dikdörtgenin kaç kenarı vardır?", ["4", "3", "5", "6"], 0, "Dikdörtgen: 4 kenar"),
    (2, 2, 4, "Top hangi şekle benzer?", ["Küre", "Küp", "Silindir", "Koni"], 0, "Top küre şeklindedir"),
    (3, 2, 4, "Zar hangi şekle benzer?", ["Küp", "Küre", "Silindir", "Koni"], 0, "Zar küp şeklindedir"),
    (3, 2, 4, "Külah hangi şekle benzer?", ["Koni", "Küp", "Küre", "Silindir"], 0, "Külah koni şeklindedir"),
    (3, 2, 4, "Kutu kola hangi şekle benzer?", ["Silindir", "Küp", "Küre", "Koni"], 0, "Silindir"),
    (3, 2, 4, "Bir kenarı 3 cm olan karenin çevresi kaçtır?", ["12 cm", "9 cm", "6 cm", "3 cm"], 0, "4 × 3 = 12 cm"),
    (3, 3, 4, "Beşgenin kaç kenarı vardır?", ["5", "4", "6", "3"], 0, "Beşgen: 5 kenar"),
    (3, 3, 4, "Altıgenin kaç kenarı vardır?", ["6", "5", "4", "7"], 0, "Altıgen: 6 kenar"),
    (4, 3, 4, "Bir kenarı 5 cm olan karenin çevresi kaçtır?", ["20 cm", "25 cm", "10 cm", "15 cm"], 0, "4 × 5 = 20 cm"),
    (4, 3, 4, "Kenarları 4 cm ve 6 cm olan dikdörtgenin çevresi kaçtır?", ["20 cm", "24 cm", "10 cm", "14 cm"], 0, "(4+6) × 2 = 20 cm"),
    (4, 3, 4, "Simetri ekseni ne demektir?", ["Şekli iki eş parçaya bölen çizgi", "Şeklin kenarı", "Şeklin köşesi", "Şeklin alanı"], 0, "Simetri ekseni şekli eş iki parçaya böler"),
    (4, 4, 4, "Dik açı kaç derecedir?", ["90°", "180°", "45°", "360°"], 0, "Dik açı = 90 derece"),
    (5, 4, 4, "Doğru açı kaç derecedir?", ["180°", "90°", "360°", "45°"], 0, "Doğru açı = 180 derece"),
    (5, 4, 4, "Bir kenarı 4 cm olan karenin alanı kaçtır?", ["16 cm²", "8 cm²", "12 cm²", "4 cm²"], 0, "4 × 4 = 16 cm²"),
    (5, 4, 4, "Karenin kaç simetri ekseni vardır?", ["4", "2", "1", "0"], 0, "Karede 4 simetri ekseni vardır"),
]

# ---------------------------------------------------------------- INGILIZCE

ING_KELIME = [
    (1, 2, 4, '"Red" ne demektir?', ["Kırmızı", "Mavi", "Sarı", "Yeşil"], 0, "red = kırmızı"),
    (1, 2, 4, '"Blue" ne demektir?', ["Mavi", "Kırmızı", "Yeşil", "Siyah"], 0, "blue = mavi"),
    (1, 2, 4, '"Yellow" ne demektir?', ["Sarı", "Mavi", "Kırmızı", "Beyaz"], 0, "yellow = sarı"),
    (1, 2, 4, '"Green" ne demektir?', ["Yeşil", "Mavi", "Sarı", "Mor"], 0, "green = yeşil"),
    (1, 2, 4, '"Cat" ne demektir?', ["Kedi", "Köpek", "Kuş", "Balık"], 0, "cat = kedi"),
    (1, 2, 4, '"Dog" ne demektir?', ["Köpek", "Kedi", "At", "Kuş"], 0, "dog = köpek"),
    (1, 2, 4, '"One" ne demektir?', ["Bir", "İki", "Üç", "Dört"], 0, "one = bir"),
    (1, 2, 4, '"Two" ne demektir?', ["İki", "Bir", "Üç", "Beş"], 0, "two = iki"),
    (2, 2, 4, '"Three" ne demektir?', ["Üç", "İki", "Dört", "Beş"], 0, "three = üç"),
    (2, 2, 4, '"Bird" ne demektir?', ["Kuş", "Balık", "Kedi", "Köpek"], 0, "bird = kuş"),
    (2, 2, 4, '"Fish" ne demektir?', ["Balık", "Kuş", "Kedi", "At"], 0, "fish = balık"),
    (2, 2, 4, '"Mother" ne demektir?', ["Anne", "Baba", "Kardeş", "Dede"], 0, "mother = anne"),
    (2, 2, 4, '"Father" ne demektir?', ["Baba", "Anne", "Abla", "Amca"], 0, "father = baba"),
    (2, 2, 4, '"Book" ne demektir?', ["Kitap", "Kalem", "Defter", "Çanta"], 0, "book = kitap"),
    (2, 2, 4, '"Pencil" ne demektir?', ["Kalem", "Kitap", "Silgi", "Cetvel"], 0, "pencil = kalem"),
    (2, 2, 4, '"Apple" ne demektir?', ["Elma", "Armut", "Muz", "Portakal"], 0, "apple = elma"),
    (3, 2, 4, '"School" ne demektir?', ["Okul", "Ev", "Park", "Market"], 0, "school = okul"),
    (3, 2, 4, '"Teacher" ne demektir?', ["Öğretmen", "Öğrenci", "Doktor", "Şoför"], 0, "teacher = öğretmen"),
    (3, 2, 4, '"Water" ne demektir?', ["Su", "Süt", "Çay", "Meyve suyu"], 0, "water = su"),
    (3, 2, 4, '"Milk" ne demektir?', ["Süt", "Su", "Çay", "Kahve"], 0, "milk = süt"),
    (3, 3, 4, '"Happy" ne demektir?', ["Mutlu", "Üzgün", "Kızgın", "Yorgun"], 0, "happy = mutlu"),
    (3, 3, 4, '"Sad" ne demektir?', ["Üzgün", "Mutlu", "Kızgın", "Şaşkın"], 0, "sad = üzgün"),
    (3, 3, 4, '"Monday" ne demektir?', ["Pazartesi", "Salı", "Pazar", "Cuma"], 0, "Monday = Pazartesi"),
    (3, 3, 4, '"Sunday" ne demektir?', ["Pazar", "Pazartesi", "Cumartesi", "Cuma"], 0, "Sunday = Pazar"),
    (4, 3, 4, '"Rainy" ne demektir?', ["Yağmurlu", "Güneşli", "Karlı", "Rüzgarlı"], 0, "rainy = yağmurlu"),
    (4, 3, 4, '"Sunny" ne demektir?', ["Güneşli", "Yağmurlu", "Bulutlu", "Karlı"], 0, "sunny = güneşli"),
    (4, 3, 4, '"Run" ne demektir?', ["Koşmak", "Yürümek", "Uyumak", "Yemek"], 0, "run = koşmak"),
    (4, 3, 4, '"Eat" ne demektir?', ["Yemek", "İçmek", "Uyumak", "Koşmak"], 0, "eat = yemek"),
    (5, 3, 4, '"January" ne demektir?', ["Ocak", "Şubat", "Mart", "Nisan"], 0, "January = Ocak"),
    (5, 3, 4, '"Grandmother" ne demektir?', ["Büyükanne", "Anne", "Teyze", "Abla"], 0, "grandmother = büyükanne"),
]

ING_IFADE = [
    (1, 2, 4, '"Hello" ne demektir?', ["Merhaba", "Hoşça kal", "Teşekkürler", "Lütfen"], 0, "Hello = Merhaba"),
    (1, 2, 4, '"Goodbye" ne demektir?', ["Hoşça kal", "Merhaba", "Günaydın", "İyi geceler"], 0, "Goodbye = Hoşça kal"),
    (1, 2, 4, '"Thank you" ne demektir?', ["Teşekkürler", "Merhaba", "Lütfen", "Özür dilerim"], 0, "Thank you = Teşekkürler"),
    (1, 2, 4, '"Please" ne demektir?', ["Lütfen", "Teşekkürler", "Merhaba", "Evet"], 0, "Please = Lütfen"),
    (2, 2, 4, '"Good morning" ne demektir?', ["Günaydın", "İyi geceler", "İyi akşamlar", "Hoşça kal"], 0, "Good morning = Günaydın"),
    (2, 2, 4, '"Good night" ne demektir?', ["İyi geceler", "Günaydın", "Merhaba", "Hoşça kal"], 0, "Good night = İyi geceler"),
    (2, 2, 4, '"Yes" ne demektir?', ["Evet", "Hayır", "Belki", "Tamam"], 0, "Yes = Evet"),
    (2, 2, 4, '"No" ne demektir?', ["Hayır", "Evet", "Belki", "Tamam"], 0, "No = Hayır"),
    (2, 2, 4, '"What is your name?" ne demektir?', ["Adın ne?", "Nasılsın?", "Kaç yaşındasın?", "Nerelisin?"], 0, "What is your name? = Adın ne?"),
    (3, 2, 4, '"How are you?" ne demektir?', ["Nasılsın?", "Adın ne?", "Kaç yaşındasın?", "Nerelisin?"], 0, "How are you? = Nasılsın?"),
    (3, 2, 4, '"I am fine" ne demektir?', ["İyiyim", "Kötüyüm", "Yorgunum", "Açım"], 0, "I am fine = İyiyim"),
    (3, 2, 4, '"My name is Ali" ne demektir?', ["Benim adım Ali", "Ali nerede?", "Ali kim?", "Ali geldi"], 0, "My name is = Benim adım"),
    (3, 3, 4, '"How old are you?" ne demektir?', ["Kaç yaşındasın?", "Nasılsın?", "Adın ne?", "Nerelisin?"], 0, "How old are you? = Kaç yaşındasın?"),
    (3, 3, 4, '"Excuse me" ne demektir?', ["Affedersiniz", "Teşekkürler", "Merhaba", "Hoşça kal"], 0, "Excuse me = Affedersiniz"),
    (4, 3, 4, '"I am sorry" ne demektir?', ["Özür dilerim", "Teşekkürler", "Rica ederim", "Merhaba"], 0, "I am sorry = Özür dilerim"),
    (4, 3, 4, '"You are welcome" ne demektir?', ["Rica ederim", "Hoşça kal", "Merhaba", "Lütfen"], 0, "You are welcome = Rica ederim"),
    (4, 3, 4, '"See you later" ne demektir?', ["Sonra görüşürüz", "Merhaba", "Teşekkürler", "İyi geceler"], 0, "See you later = Sonra görüşürüz"),
    (5, 3, 4, '"Nice to meet you" ne demektir?', ["Tanıştığımıza memnun oldum", "Nasılsın?", "Hoşça kal", "Teşekkürler"], 0, "Nice to meet you = Tanıştığımıza memnun oldum"),
    (5, 3, 4, '"Where are you from?" ne demektir?', ["Nerelisin?", "Nasılsın?", "Adın ne?", "Kaç yaşındasın?"], 0, "Where are you from? = Nerelisin?"),
    (1, 2, 4, '"Good afternoon" ne demektir?', ["İyi günler", "Günaydın", "İyi geceler", "Hoşça kal"], 0, "Good afternoon = İyi günler"),
    (1, 2, 4, '"Bye" ne demektir?', ["Güle güle", "Merhaba", "Lütfen", "Evet"], 0, "Bye = Güle güle"),
    (2, 2, 4, '"Good evening" ne demektir?', ["İyi akşamlar", "Günaydın", "İyi günler", "Merhaba"], 0, "Good evening = İyi akşamlar"),
    (2, 2, 4, '"I am Ali" ne demektir?', ["Ben Ali'yim", "Ali nerede?", "Ali geldi", "Ali kim?"], 0, "I am = Ben ...-im"),
    (2, 2, 4, '"Sit down" ne demektir?', ["Otur", "Kalk", "Gel", "Git"], 0, "Sit down = Otur"),
    (3, 2, 4, '"Stand up" ne demektir?', ["Ayağa kalk", "Otur", "Uyu", "Koş"], 0, "Stand up = Ayağa kalk"),
    (3, 2, 4, '"Open your book" ne demektir?', ["Kitabını aç", "Kitabını kapat", "Kitabını ver", "Kitabını al"], 0, "Open = Aç"),
    (3, 3, 4, '"Listen to me" ne demektir?', ["Beni dinle", "Bana bak", "Beni bekle", "Bana gel"], 0, "Listen = Dinle"),
    (4, 3, 4, '"Come here" ne demektir?', ["Buraya gel", "Oraya git", "Burada kal", "Dışarı çık"], 0, "Come here = Buraya gel"),
    (4, 3, 4, '"I like apples" ne demektir?', ["Elmaları severim", "Elma yerim", "Elmam var", "Elma isterim"], 0, "I like = Severim"),
    (5, 3, 4, '"How is the weather?" ne demektir?', ["Hava nasıl?", "Nasılsın?", "Saat kaç?", "Neredesin?"], 0, "How is the weather? = Hava nasıl?"),
]
